server:
  port: 8080

spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:5173"
              - "http://localhost:5174"
            allowedMethods: [GET, POST, PUT, DELETE, OPTIONS]
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
        - id: stock-service
          uri: lb://stock-service
          predicates:
            - Path=/api/stocks/**
        - id: portfolio-service
          uri: lb://portfolio-service
          predicates:
            - Path=/api/portfolio/**
        - id: threshold-service
          uri: lb://threshold-service
          predicates:
            - Path=/api/thresholds/**
